spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taiying
    username: tyopr
    password: ty1234
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:sqlmap/*.xml