spring:
  datasource:
    url: jdbc:mysql://rm-wz9h95286k55xg3hy.mysql.rds.aliyuncs.com:3306/taiying-stg
    username: tyopr
    password: ty1234
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:sqlmap/*.xml
server:
  port: 8888
